
%% One-way analysis of wind_d1...
% wind_test = [double(IBTrACS_acyc(:,15)),randsample(double(IBTrACS_cyc(:,15)),7856),...
%     randsample(double(IBTrACS_miss(:,15)),7856)];
% 
% anova1(wind_test)

%% One-way analysis of wind_d2...
wind_test = [double(IBTrACS_acyc(:,16)),randsample(double(IBTrACS_cyc(:,16)),7856),...
    randsample(double(IBTrACS_miss(:,16)),7856)];

anova1(wind_test)